---
name: nagios.service.check_proc
description: Check process state on host
enabled: true
trigger:
  type: st2.nagios.service.state_change
criteria:
  service:
    pattern: "(.*)_check_(.*)_process"
    type: matchregex
  state_type:
    pattern: HARD
    type: matchregex
action:
  ref: check_pgrep
  parameters:
    hosts: "{{trigger.host}}"
    cmd: "{{trigger.service}} 1 10"
